# Generated by Django 5.1.3 on 2026-06-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikkiinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True, verbose_name='URL-адрес'),
        ),
    ]
