# Generated by Django 5.1.3 on 2026-06-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikkiinfo', '0002_alter_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='URL-адрес'),
        ),
        migrations.AlterField(
            model_name='voiceactor',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True, verbose_name='URL-адрес'),
        ),
    ]
