# Generated by Django 5.1.3 on 2026-06-04 11:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikkiinfo', '0003_alter_anime_slug_alter_voiceactor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='release_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2100, 12, 31))], verbose_name='Год выпуска'),
        ),
    ]
